### PR TITLE
image deploy: fix message of no nodes in app pool

### LINKED ISSUE #1482: Image deploy: wrong error message when there are no nodes in application pool
When trying to deploy an application associated to a pool whose contains no nodes, tsuru behaves differently for different kinds of deployment.

Upload:

```
% tsuru app-deploy -a chico-dev index.html
Uploading files (0.00MB)... 0.00% (0.00MB/s)Error: error in scheduler: No nodes found with one of the following metadata: pool=dev\dev.example.com
```

Image:

```
% tsuru app-deploy -a chico-dev -i whatever
Deploying image... ok
---- Pulling image to tsuru ----
invalid endpoint
```

### PR DESCRIPTION
**Pull request by ArxdSilva**
fixes #1482

### CODE REVIEW

File: provision/docker/provisioner_test.go [hunk 1]
```diff
@@ -1026,6 +1027,62 @@ func (s *S) TestImageDeploy(c *check.C) {
...
+	err = provision.AddPool(opts)
+	c.Assert(err, check.IsNil)
+	p.storage = &cluster.MapStorage{}
+	c.Assert(err, check.IsNil)
+	mainDockerProvisioner = &p
+	u, _ := url.Parse(s.server.URL())
+	imageName := fmt.Sprintf("%s/%s", u.Host, "customimage")
+	config.Set("docker:registry", u.Host)
+	defer config.Unset("docker:registry")
+	s.server.CustomHandler("/containers/.*/attach", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (andrestc) [inline provision/docker/provisioner_test.go]: Is this customHandler needed?
