### PR TITLE
api: uses header to decide error verbosity

### LINKED ISSUE #1647: Stack trace being printed on client when adding platforms without nodes
We should handle this and maybe only display they stack track on verbose.

```
$ tsuru platform add static
Error: There is no Docker node. Add one with `tsuru node-add`
github.com/tsuru/tsuru/provision/docker.(*dockerProvisioner).GetDockerClient
	/go/src/github.com/tsuru/tsuru/provision/docker/docker.go:178
github.com/tsuru/tsuru/builder/docker.getDockerClient
	/go/src/github.com/tsuru/tsuru/builder/docker/platform.go:121
github.com/tsuru/tsuru/builder/docker.(*dockerBuilder).buildPlatform
	/go/src/github.com/tsuru/tsuru/builder/docker/platform.go:65
github.com/tsuru/tsuru/builder/docker.(*dockerBuilder).PlatformAdd
	/go/src/github.com/tsuru/tsuru/builder/docker/platform.go:30
github.com/tsuru/tsuru/builder.PlatformAdd
	/go/src/github.com/tsuru/tsuru/builder/builder.go:90
github.com/tsuru/tsuru/app.PlatformAdd
	/go/src/github.com/tsuru/tsuru/app/platform.go:82
github.com/tsuru/tsuru/api.platformAdd
	/go/src/github.com/tsuru/tsuru/api/platform.go:64
github.com/tsuru/tsuru/api.AuthorizationRequiredHandler.ServeHTTP
	/go/src/github.com/tsuru/tsuru/api/handler.go:36
github.com/tsuru/tsuru/api.runDelayedHandler
	/go/src/github.com/tsuru/tsuru/api/middleware.go:226
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1942
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.Wrap.func1
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:41
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.(*appLockMiddleware).ServeHTTP
	/go/src/github.com/tsuru/tsuru/api/middleware.go:173
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.authTokenMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:144
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.setVersionHeadersMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:99
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.errorHandlingMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:103
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.setRequestIDHeaderMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:78
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33 no swarm nodes available

github.com/tsuru/tsuru/provision/swarm.chooseDBSwarmNode
	/go/src/github.com/tsuru/tsuru/provision/swarm/db.go:53
github.com/tsuru/tsuru/provision/swarm.(*swarmProvisioner).GetDockerClient
	/go/src/github.com/tsuru/tsuru/provision/swarm/provisioner.go:623
github.com/tsuru/tsuru/builder/docker.getDockerClient
	/go/src/github.com/tsuru/tsuru/builder/docker/platform.go:121
github.com/tsuru/tsuru/builder/docker.(*dockerBuilder).buildPlatform
	/go/src/github.com/tsuru/tsuru/builder/docker/platform.go:65
github.com/tsuru/tsuru/builder/docker.(*dockerBuilder).PlatformAdd
	/go/src/github.com/tsuru/tsuru/builder/docker/platform.go:30
github.com/tsuru/tsuru/builder.PlatformAdd
	/go/src/github.com/tsuru/tsuru/builder/builder.go:90
github.com/tsuru/tsuru/app.PlatformAdd
	/go/src/github.com/tsuru/tsuru/app/platform.go:82
github.com/tsuru/tsuru/api.platformAdd
	/go/src/github.com/tsuru/tsuru/api/platform.go:64
github.com/tsuru/tsuru/api.AuthorizationRequiredHandler.ServeHTTP
	/go/src/github.com/tsuru/tsuru/api/handler.go:36
github.com/tsuru/tsuru/api.runDelayedHandler
	/go/src/github.com/tsuru/tsuru/api/middleware.go:226
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1942
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.Wrap.func1
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:41
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.(*appLockMiddleware).ServeHTTP
	/go/src/github.com/tsuru/tsuru/api/middleware.go:173
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.authTokenMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:144
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.setVersionHeadersMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:99
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.errorHandlingMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:103
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:33
github.com/tsuru/tsuru/api.setRequestIDHeaderMiddleware
	/go/src/github.com/tsuru/tsuru/api/middleware.go:78
github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/tsuru/tsuru/vendor/github.com/codegangsta/negroni/negroni.go:24
```

### PR DESCRIPTION
**Pull request by andrestc**
This PR adds a header to control how verbose errors are sent to clients, i.e if they include a stack trace. This header is set using the `--verbosity` flag on our client.

Fixes #1647

### CODE REVIEW

File: api/middleware.go [hunk 1]
```diff
@@ -103,13 +105,22 @@ func errorHandlingMiddleware(w http.ResponseWriter, r *http.Request, next http.H
 	next(w, r)
 	err := context.GetRequestError(r)
 	if err != nil {
+		verbosity, errConv := strconv.Atoi(r.Header.Get(cmd.VerbosityHeader))
```
Comment (cezarsa) [inline api/middleware.go]: I think it's safe to simply ignore the error here, verbosity will be 0 anyway.
